FROM ubuntu:20.04 AS builder

WORKDIR /builder

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y  \
	libgstreamer1.0-0 \
	gstreamer1.0-plugins-base \
	gstreamer1.0-plugins-good \
	gstreamer1.0-plugins-bad \
	gstreamer1.0-plugins-ugly \
	gstreamer1.0-libav \
	gstreamer1.0-doc \
	gstreamer1.0-tools \
	libgstreamer1.0-dev \
	libgstreamer-plugins-base1.0-dev \
	pkg-config \
	git \
	m4 \
	build-essential \
	cmake \
	ninja-build


RUN git clone https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp.git .
RUN mkdir build && cd build && \
	cmake .. -DBUILD_GSTREAMER_PLUGIN=ON -DBUILD_DEPENDENCIES=OFF && \
    make

FROM scratch AS export-stage
COPY --from=builder /builder/build build
