FROM python:3.9-buster AS builder

WORKDIR /builder

RUN apt-get update && apt-get upgrade -y

RUN \
	apt-get install -y \
	libgstreamer1.0-0 \
	gstreamer1.0-plugins-base \
	gstreamer1.0-plugins-good \
	gstreamer1.0-plugins-bad \
	gstreamer1.0-plugins-ugly \
	gstreamer1.0-libav \
	gstreamer1.0-doc \
	gstreamer1.0-tools \
	libgstreamer1.0-dev \
	libgstreamer-plugins-base1.0-dev \
	libjpeg-dev \
	git \
	ninja-build

# get opencv and build it
RUN git clone --recursive https://github.com/opencv/opencv-python.git .

ENV CMAKE_ARGS="-DCMAKE_BUILD_TYPE=RELEASE -DWITH_GSTREAMER=ON -DBUILD_JPEG=ON"
ENV ENABLE_HEADLESS=1
RUN pip wheel . --verbose

FROM scratch AS export-stage
COPY --from=builder /builder/opencv*.whl .
