FROM ubuntu:20.04 AS builder

WORKDIR /kinesis

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y  \
	libssl-dev \
	libcurl4-openssl-dev \
	liblog4cplus-dev \
	libgstreamer1.0-0 \
	gstreamer1.0-plugins-base \
	gstreamer1.0-plugins-good \
	gstreamer1.0-plugins-bad \
	gstreamer1.0-plugins-ugly \
	gstreamer1.0-libav \
	gstreamer1.0-doc \
	gstreamer1.0-tools \
	libgstreamer1.0-dev \
	libgstreamer-plugins-base1.0-dev \
	pkg-config \
	git \
	m4 \
	build-essential \
	cmake

RUN git clone https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp.git .

# Apply patch
COPY kinesis-patch.diff .
RUN git apply kinesis-patch.diff

RUN mkdir build && cd build && \
	cmake .. -DBUILD_GSTREAMER_PLUGIN=ON -DBUILD_DEPENDENCIES=OFF -DBUILD_STATIC=1 && \
    make

FROM scratch AS export-stage
COPY --from=builder /kinesis/build .
