name: Development packaging

on:
  push:
    branches:
      - 'main'

env:
  IMAGE_NAME: opencv-builder

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Run docker container
        run: docker run --rm -v $PWD/build:/build $IMAGE_NAME bash

      - name: Upload image
        uses: actions/upload-artifact@v3
        with:
          name: builds
          path: |
            build/*.whl
