name: Development packaging

on:
  push:
    branches:
      - 'main'

env:
  IMAGE_NAME: opencv-builder

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64 \
          -f Dockerfile \
          -t $IMAGE_NAME \
          --output build .

      - name: Run ls
        run: ls -l build/linux_amd64

      - name: Upload image
        uses: actions/upload-artifact@v3
        with:
          path: |
            build/
